# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager with iTerm2 integration"
  homepage "https://github.com/joescharf/wt"
  version "0.5.1"
  license "MIT"
  depends_on :macos

  url "https://github.com/joescharf/wt/releases/download/v0.5.1/wt_darwin_universal.tar.gz"
  sha256 "ba589be68a53d0311765054adf0bdcba5fd1f559a37b4fbe8e547f61e8690fe1"

  def install
    bin.install "wt"
  end
end
