# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager with iTerm2 integration"
  homepage "https://github.com/joescharf/wt"
  version "0.5.3"
  license "MIT"
  depends_on :macos

  url "https://github.com/joescharf/wt/releases/download/v0.5.3/wt_darwin_universal.tar.gz"
  sha256 "3f4bdd303620a641f95d9f097f86375d7d4adfd59e41b56238d59164b096ed8e"

  def install
    bin.install "wt"
  end
end
