# This file was generated by GoReleaser. DO NOT EDIT.
cask "berkshire" do
  name "berkshire"
  desc "Description of berkshire"
  homepage "https://github.com/joescharf/berkshire"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "berkshire"

  on_macos do
    url "https://github.com/joescharf/berkshire/releases/download/v#{version}/berkshire_Darwin_universal.zip"
    sha256 "46848769afa99ad7d6d23d1a3f53b72cb7b429663f17ec21d820b26ff5b7fe3c"
  end

  # No zap stanza required
end
