# This file was generated by GoReleaser. DO NOT EDIT.
cask "clonit" do
  version "0.2.0"

  on_macos do
    sha256 "09a72bc69a4ac8250606b67b55dfed61e54be567f259be4c2b9e76e9ae91c94d"
    url "https://pub-816a8822a6ce404ab522aa73c8f47274.r2.dev/releases/#{version}/clonit_Darwin_universal.zip"
  end

  name "clonit"
  desc "Database snapshotting, sanitizing, and sharing CLI tool."
  homepage "https://clonit.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clonit"

  # No zap stanza required

end
