# This file was generated by GoReleaser. DO NOT EDIT.
cask "clonit" do
  version "0.5.0"

  on_macos do
    sha256 "2c7a52cb917fa84e4d81dff947567ffc93d415542a88f176e907154f24f3b9ef"
    url "https://pub-816a8822a6ce404ab522aa73c8f47274.r2.dev/releases/#{version}/clonit_Darwin_universal.zip"
  end

  name "clonit"
  desc "Database snapshotting, sanitizing, and sharing CLI tool."
  homepage "https://clonit.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clonit"

  # No zap stanza required

end
