# This file was generated by GoReleaser. DO NOT EDIT.
cask "clonit" do
  version "0.5.1"

  on_macos do
    sha256 "80bd4f22d7236a5f326446134d7f4bb379ac916b39ee88b459ccf1494a7941ee"
    url "https://pub-816a8822a6ce404ab522aa73c8f47274.r2.dev/releases/#{version}/clonit_Darwin_universal.zip"
  end

  name "clonit"
  desc "Database snapshotting, sanitizing, and sharing CLI tool."
  homepage "https://clonit.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clonit"

  # No zap stanza required

end
