# This file was generated by GoReleaser. DO NOT EDIT.
cask "fdsn" do
  name "fdsn"
  desc "Seismic station metadata management -- import, explore, and re-serve FDSN data from a single binary."
  homepage "https://github.com/joescharf/fdsn"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fdsn"

  on_macos do
    url "https://github.com/joescharf/fdsn/releases/download/v#{version}/fdsn_Darwin_universal.zip"
    sha256 "6415d560bd04c8d654989751468932056f32bafa25fa461da4c35fca6aea665b"
  end

  # No zap stanza required
end
