# This file was generated by GoReleaser. DO NOT EDIT.
cask "fdsn" do
  name "fdsn"
  desc "Seismic station metadata management -- import, explore, and re-serve FDSN data from a single binary."
  homepage "https://github.com/joescharf/fdsn"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fdsn"

  on_macos do
    url "https://github.com/joescharf/fdsn/releases/download/v#{version}/fdsn_#{version}_darwin_all.zip"
    sha256 "3f6ef870d2737128e279a32e35d510e6f8bf46f79d3c742c82c97e942b989a8c"
  end

  # No zap stanza required
end
