# This file was generated by GoReleaser. DO NOT EDIT.
cask "gsi" do
  name "gsi"
  desc "Initialize Go projects with best practices and tooling"
  homepage "https://github.com/joescharf/gsi"
  version "0.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gsi"

  on_macos do
    url "https://github.com/joescharf/gsi/releases/download/v#{version}/gsi_Darwin_universal.zip"
    sha256 "820817fc50aad82e48b3a2c6dffb999a0e2db2b66e4e7c6b1ccd2eeb82f82d6d"
  end

  # No zap stanza required
end
