# This file was generated by GoReleaser. DO NOT EDIT.
cask "gsi" do
  name "gsi"
  desc "Initialize Go projects with best practices and tooling"
  homepage "https://github.com/joescharf/gsi"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gsi"

  on_macos do
    url "https://github.com/joescharf/gsi/releases/download/v#{version}/gsi_Darwin_universal.zip"
    sha256 "8e4eab83f93c0be3b65ddb341f71740ae369a5a3738a5f1c7877b1fc337a4ea8"
  end

  # No zap stanza required
end
