# This file was generated by GoReleaser. DO NOT EDIT.
cask "gsi" do
  name "gsi"
  desc "Initialize Go projects with best practices and tooling"
  homepage "https://github.com/joescharf/gsi"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gsi"

  on_macos do
    url "https://github.com/joescharf/gsi/releases/download/v#{version}/gsi_#{version}_darwin_all.zip"
    sha256 "201ffa77265bfe45345d0706baae84f86541ad48209d207e842db1b0f1b1bc78"
  end

  # No zap stanza required
end
