# This file was generated by GoReleaser. DO NOT EDIT.
cask "pm" do
  name "pm"
  desc "Project manager CLI — track projects, issues, and agent sessions from a single binary."
  homepage "https://github.com/joescharf/pm"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pm"

  on_macos do
    on_intel do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_darwin_amd64.tar.gz"
      sha256 "ab63fad65db4c43a8620c1bdc244dd043d79ff556deb61a4c2b22fd212358585"
    end
    on_arm do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_darwin_arm64.tar.gz"
      sha256 "ae049c0daf18ef71a428ce7bf83c3c07172f127a559600bbdacd29f9e6b70e39"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_linux_amd64.tar.gz"
      sha256 "aafb5c3572fce0b119de6da86b279ef7cf6dfb220efcd7fcf68aa628fedb058e"
    end
    on_arm do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_linux_arm64.tar.gz"
      sha256 "835e15f41c30f87999f86e8649f134ea3fd49130d895bbb7e95c483fdce688b3"
    end
  end

  # No zap stanza required
end
