# This file was generated by GoReleaser. DO NOT EDIT.
cask "pm" do
  name "pm"
  desc "Project manager CLI — track projects, issues, and agent sessions from a single binary."
  homepage "https://github.com/joescharf/pm"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pm"

  on_macos do
    on_intel do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_darwin_amd64.tar.gz"
      sha256 "2ae52bd41ab99147da785a376aa72d13693731dc660fc190c64d525d15642bb3"
    end
    on_arm do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_darwin_arm64.tar.gz"
      sha256 "51e16b36283d97f61de3aedd38537ea6ea2a591dd3643e71ec292de00282c8b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_linux_amd64.tar.gz"
      sha256 "ba0b2056322473a6321bb30d70f03a1fbbca81cd59ff24d3a775a6c3e6b4d58c"
    end
    on_arm do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_linux_arm64.tar.gz"
      sha256 "58201f20742987a42ed27caf0bcce86dc762548e083eae9f29e217ed58380aea"
    end
  end

  # No zap stanza required
end
