# This file was generated by GoReleaser. DO NOT EDIT.
cask "pm" do
  name "pm"
  desc "Project manager CLI — track projects, issues, and agent sessions from a single binary."
  homepage "https://github.com/joescharf/pm"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pm"

  on_macos do
    on_intel do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_darwin_amd64.tar.gz"
      sha256 "b307bb077192bc06558b96918195a3452da7693f3efe5464a27ec20f207a81e4"
    end
    on_arm do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_darwin_arm64.tar.gz"
      sha256 "017bdfd5857a6fcacd68320578e825249c67ddfb199ba37e2fb6bebc7b9f4845"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_linux_amd64.tar.gz"
      sha256 "860c268f476887b1c3f69b26806a4e0902022e66e8113456fa23ddf7f49672bb"
    end
    on_arm do
      url "https://github.com/joescharf/pm/releases/download/v#{version}/pm_#{version}_linux_arm64.tar.gz"
      sha256 "d15a2388fe9e2b1b377e2287540f7fe549c9b5cb6c65d7d7a19c7bd8ebd8ed18"
    end
  end

  # No zap stanza required
end
