# This file was generated by GoReleaser. DO NOT EDIT.
cask "quantana-cloud" do
  version "0.2.0"

  on_macos do
    sha256 "ed8f644066802edc2d58d996710fdd4f9be924fb992fa5b92eb186ce0113ee87"
    url "https://github.com/joescharf/quantana-cloud/releases/download/v#{version}/quantana-cloud_Darwin_universal.zip"
  end

  name "quantana-cloud"
  desc "Description of quantana-cloud"
  homepage "https://github.com/joescharf/quantana-cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quantana-cloud"

  # No zap stanza required

end
