# This file was generated by GoReleaser. DO NOT EDIT.
cask "quantana-cloud" do
  version "0.1.0"

  on_macos do
    sha256 "280ca635881111c2f1f379b89722bdc9364c0f1ff6a9a540036c4aae1d613f76"
    url "https://github.com/joescharf/quantana-cloud/releases/download/v#{version}/quantana-cloud_Darwin_universal.zip"
  end

  name "quantana-cloud"
  desc "Description of quantana-cloud"
  homepage "https://github.com/joescharf/quantana-cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quantana-cloud"

  # No zap stanza required

end
