# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager with iTerm2 integration"
  homepage "https://github.com/joescharf/wt"
  version "0.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    url "https://github.com/joescharf/wt/releases/download/v#{version}/wt_darwin_universal.zip"
    sha256 "61e4d8b809271fea2c001f250265c706ed2b956131ea0b9791ae288843bdd137"
  end

  # No zap stanza required
end
