# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager with iTerm2 integration"
  homepage "https://github.com/joescharf/wt"
  version "0.5.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    url "https://github.com/joescharf/wt/releases/download/v#{version}/wt_darwin_universal.zip"
    sha256 "34590aa11fb4722f8e19ee6f6505f88c0686d6ef549ecb9a1d4cb0bbfa412df7"
  end

  # No zap stanza required
end
