# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fdsn < Formula
  desc "Seismic station metadata management -- import, explore, and re-serve FDSN data from a single binary."
  homepage "https://github.com/joescharf/fdsn"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joescharf/fdsn/releases/download/v0.2.0/fdsn_0.2.0_darwin_amd64.tar.gz"
      sha256 "7281ca9bac155a8e644ee7a7cf35b7cb0ddb1b96cef9474b24c30b2e246051b6"

      def install
        bin.install "fdsn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joescharf/fdsn/releases/download/v0.2.0/fdsn_0.2.0_darwin_arm64.tar.gz"
      sha256 "60c13b4c3e01023b6c1496d7dd357dec08b44b7596ba7c221d8a1e6c7c1134aa"

      def install
        bin.install "fdsn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joescharf/fdsn/releases/download/v0.2.0/fdsn_0.2.0_linux_amd64.tar.gz"
      sha256 "865b91627b88bc925ca4bb5ccb26594e249463f13b9e6244bdeef372f2c2fca8"
      def install
        bin.install "fdsn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joescharf/fdsn/releases/download/v0.2.0/fdsn_0.2.0_linux_arm64.tar.gz"
      sha256 "5f2d8bbf7b56d96aad2d5987403cd992e321d0f93034be82749d117bc58b79f9"
      def install
        bin.install "fdsn"
      end
    end
  end

  test do
    system "#{bin}/fdsn", "version"
  end
end
