# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fdsn < Formula
  desc "Seismic station metadata management -- import, explore, and re-serve FDSN data from a single binary."
  homepage "https://github.com/joescharf/fdsn"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joescharf/fdsn/releases/download/v0.1.0/fdsn_0.1.0_darwin_amd64.tar.gz"
      sha256 "db4ccefe15a4267a5d5d2609f4c3723663315dcc39ae111e1ef3c5325b65f881"

      def install
        bin.install "fdsn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joescharf/fdsn/releases/download/v0.1.0/fdsn_0.1.0_darwin_arm64.tar.gz"
      sha256 "52b5b16627ed3208beac1558a5bfe23bc819841a494f7dfa0e056b5561ffb414"

      def install
        bin.install "fdsn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joescharf/fdsn/releases/download/v0.1.0/fdsn_0.1.0_linux_amd64.tar.gz"
      sha256 "54fccaf4ccfdc6b49990c4fb1d2dc525e7a908dd1544e4b0bebb4825b3663a4b"
      def install
        bin.install "fdsn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joescharf/fdsn/releases/download/v0.1.0/fdsn_0.1.0_linux_arm64.tar.gz"
      sha256 "8d67a213e334d998dce39bc49c4599c4face3ab62cf627f2d4804b6824bb09e4"
      def install
        bin.install "fdsn"
      end
    end
  end

  test do
    system "#{bin}/fdsn", "version"
  end
end
